// gittomd core 1.0.1 for the browser. Generated by scripts/build-web.mjs; do not edit.
// https://github.com/Ismael-Sallami/gittomd (MIT)
(function (global) {
  "use strict";

  // ---- i18n.js ----
  // Texts used in the generated Markdown and in the CLI, in Spanish and English.
  // Plain wording on purpose: no long dashes, no decorative symbols.

  const MESSAGES = {
    es: {
      generatedBy: "Generado con gittomd el {date}.",
      promptTitle: "Instrucciones para la IA",
      defaultPrompt:
        "Abajo tienes el contenido completo del repositorio {repo}: primero un resumen, luego la estructura de carpetas y después cada fichero. " +
        "Explícame qué hace el proyecto, cómo está organizado, cómo se instala y se ejecuta, y cuáles son sus partes principales. " +
        "Cuando hables de un fichero, cita su ruta.",
      summary: "Resumen",
      source: "Origen",
      description: "Descripción",
      ref: "Rama o ref",
      commit: "Commit",
      included: "Ficheros incluidos",
      skipped: "Ficheros omitidos",
      size: "Tamaño del contenido",
      tokens: "Tokens estimados",
      part: "Parte",
      of: "de",
      structure: "Estructura",
      files: "Ficheros",
      skippedTitle: "Ficheros omitidos",
      skippedIntro: "Estos ficheros aparecen en la estructura pero su contenido no se ha incluido.",
      file: "Fichero",
      reason: "Motivo",
      omittedMark: "[omitido]",
      filesInside: "{n} ficheros dentro",
      emptyFile: "(fichero vacío)",
      more: "Y {n} más.",
      reasons: {
        "ignored-dir": "carpeta ignorada por defecto",
        gitignore: "ignorado por .gitignore",
        gittomdignore: "ignorado por .gittomdignore",
        exclude: "excluido con --exclude",
        "not-included": "no coincide con --include",
        "outside-subdir": "fuera de la subcarpeta",
        lockfile: "fichero de bloqueo de dependencias",
        binary: "fichero binario",
        minified: "fichero minificado o mapa de código",
        "too-large": "supera el tamaño máximo por fichero",
        "total-limit": "se alcanzó el límite total",
        symlink: "enlace simbólico",
        "no-contents": "contenido desactivado con --no-contents",
        "fetch-error": "no se pudo descargar",
        "user-excluded": "desmarcado a mano",
      },
    },
    en: {
      generatedBy: "Generated with gittomd on {date}.",
      promptTitle: "Instructions for the AI",
      defaultPrompt:
        "Below is the full content of the repository {repo}: first a summary, then the folder structure and then every file. " +
        "Explain what the project does, how it is organised, how to install and run it, and what its main parts are. " +
        "When you talk about a file, quote its path.",
      summary: "Summary",
      source: "Source",
      description: "Description",
      ref: "Branch or ref",
      commit: "Commit",
      included: "Files included",
      skipped: "Files skipped",
      size: "Content size",
      tokens: "Estimated tokens",
      part: "Part",
      of: "of",
      structure: "Structure",
      files: "Files",
      skippedTitle: "Skipped files",
      skippedIntro: "These files appear in the structure but their content was left out.",
      file: "File",
      reason: "Reason",
      omittedMark: "[skipped]",
      filesInside: "{n} files inside",
      emptyFile: "(empty file)",
      more: "And {n} more.",
      reasons: {
        "ignored-dir": "folder ignored by default",
        gitignore: "ignored by .gitignore",
        gittomdignore: "ignored by .gittomdignore",
        exclude: "excluded with --exclude",
        "not-included": "does not match --include",
        "outside-subdir": "outside the subfolder",
        lockfile: "dependency lock file",
        binary: "binary file",
        minified: "minified file or source map",
        "too-large": "larger than the per-file limit",
        "total-limit": "total limit reached",
        symlink: "symbolic link",
        "no-contents": "contents disabled with --no-contents",
        "fetch-error": "could not be downloaded",
        "user-excluded": "unticked by hand",
      },
    },
  };

  function pickLang(value) {
    const v = String(value || "").toLowerCase();
    if (v.startsWith("es")) return "es";
    if (v.startsWith("en")) return "en";
    return null;
  }

  function t(lang, key, vars) {
    const table = MESSAGES[lang] || MESSAGES.es;
    let text = key.split(".").reduce((o, k) => (o ? o[k] : undefined), table);
    if (text === undefined) text = key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) text = text.split(`{${k}}`).join(String(v));
    }
    return text;
  }

  // ---- gitignore.js ----
  // Glob and .gitignore matching without dependencies.
  //
  // Supported: *, **, ?, [abc], [!abc], {a,b}, negation with !, trailing / for
  // folders only, leading / to anchor, and escaped characters with \.

  function globToRegExp(glob) {
    let re = "";
    let i = 0;
    let inBraces = 0;
    while (i < glob.length) {
      const c = glob[i];
      if (c === "\\" && i + 1 < glob.length) {
        re += escapeRe(glob[i + 1]);
        i += 2;
        continue;
      }
      if (c === "*") {
        if (glob[i + 1] === "*") {
          const before = i === 0 || glob[i - 1] === "/";
          const after = i + 2 === glob.length || glob[i + 2] === "/";
          if (before && after) {
            if (i + 2 === glob.length) {
              re += ".*";
              i += 2;
            } else {
              // "**/" matches zero or more folders
              re += "(?:.*/)?";
              i += 3;
            }
            continue;
          }
          re += "[^/]*";
          i += 2;
          continue;
        }
        re += "[^/]*";
        i += 1;
        continue;
      }
      if (c === "?") {
        re += "[^/]";
        i += 1;
        continue;
      }
      if (c === "[") {
        const end = glob.indexOf("]", i + 2);
        if (end === -1) {
          re += "\\[";
          i += 1;
          continue;
        }
        let body = glob.slice(i + 1, end);
        if (body[0] === "!" || body[0] === "^") body = "^" + body.slice(1);
        re += "[" + body.replace(/\\/g, "\\\\") + "]";
        i = end + 1;
        continue;
      }
      if (c === "{") {
        inBraces += 1;
        re += "(?:";
        i += 1;
        continue;
      }
      if (c === "}" && inBraces > 0) {
        inBraces -= 1;
        re += ")";
        i += 1;
        continue;
      }
      if (c === "," && inBraces > 0) {
        re += "|";
        i += 1;
        continue;
      }
      re += escapeRe(c);
      i += 1;
    }
    while (inBraces-- > 0) re += ")";
    return re;
  }

  function escapeRe(c) {
    return /[.*+?^${}()|[\]\\/]/.test(c) ? "\\" + c : c;
  }

  // Parses the text of an ignore file into rules. `base` is the folder that holds
  // the file, relative to the repo root ("" for the root).
  function parseIgnore(text, base = "") {
    const rules = [];
    for (let raw of String(text).split(/\r?\n/)) {
      let line = raw.replace(/(?<!\\)\s+$/, "");
      if (!line || line.startsWith("#")) continue;
      let negate = false;
      if (line.startsWith("!")) {
        negate = true;
        line = line.slice(1);
      } else if (line.startsWith("\\!") || line.startsWith("\\#")) {
        line = line.slice(1);
      }
      let dirOnly = false;
      if (line.endsWith("/")) {
        dirOnly = true;
        line = line.replace(/\/+$/, "");
      }
      if (!line) continue;
      // A slash at the start or in the middle anchors the pattern to `base`.
      const anchored = line.includes("/");
      if (line.startsWith("/")) line = line.slice(1);
      const body = globToRegExp(line);
      const prefix = base ? escapeGlobBase(base) + "/" : "";
      const source = anchored ? `^${prefix}${body}$` : `^${prefix}(?:.*/)?${body}$`;
      rules.push({ re: new RegExp(source), negate, dirOnly, base });
    }
    return rules;
  }

  function escapeGlobBase(base) {
    return base.split("").map(escapeRe).join("");
  }

  // Builds a matcher from a list of rules (in order: later rules win).
  // Returns a function (path) => boolean, where true means ignored.
  // Git never looks inside an ignored folder, so a file is ignored when any of
  // its parent folders is.
  function createMatcher(rules) {
    if (!rules.length) return () => false;
    const dirCache = new Map();

    function test(path, isDir) {
      let result = false;
      for (const rule of rules) {
        if (rule.dirOnly && !isDir) continue;
        if (rule.base && !path.startsWith(rule.base + "/")) continue;
        if (rule.re.test(path)) result = !rule.negate;
      }
      return result;
    }

    function dirIgnored(dir) {
      if (dirCache.has(dir)) return dirCache.get(dir);
      const slash = dir.lastIndexOf("/");
      const parent = slash === -1 ? "" : dir.slice(0, slash);
      const value = (parent && dirIgnored(parent)) || test(dir, true);
      dirCache.set(dir, value);
      return value;
    }

    return function ignored(path) {
      const slash = path.lastIndexOf("/");
      if (slash !== -1 && dirIgnored(path.slice(0, slash))) return true;
      return test(path, false);
    };
  }

  // Simple glob matcher for --include / --exclude. A pattern without a slash
  // matches the file name at any depth; a pattern ending in / matches a folder.
  function createGlobList(patterns) {
    const list = (patterns || []).filter(Boolean);
    if (!list.length) return null;
    return createMatcher(parseIgnore(list.join("\n")));
  }

  // ---- filters.js ----
  // Decides, file by file, whether the content goes into the Markdown and, if
  // not, why. Works with paths and sizes only, so the web version can filter
  // before downloading anything.


  // Folders that are almost never useful to an AI reading the code.
  const IGNORED_DIRS = [
    ".git", ".hg", ".svn", "node_modules", "bower_components", "__pycache__",
    ".venv", "venv", ".tox", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    ".next", ".nuxt", ".svelte-kit", ".turbo", ".parcel-cache", ".cache",
    ".gradle", ".idea", ".vs", "coverage", ".nyc_output",
  ];

  const LOCKFILES = [
    "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml",
    "bun.lockb", "bun.lock", "deno.lock", "poetry.lock", "Pipfile.lock", "uv.lock",
    "pdm.lock", "Cargo.lock", "go.sum", "composer.lock", "Gemfile.lock",
    "mix.lock", "pubspec.lock", "Podfile.lock", "packages.lock.json",
    "flake.lock", "gradle.lockfile", "conan.lock",
  ];

  const JUNK_FILES = [".DS_Store", "Thumbs.db", "desktop.ini"];

  const BINARY_EXTENSIONS = [
    // images
    "png", "jpg", "jpeg", "gif", "bmp", "ico", "icns", "webp", "avif", "tif", "tiff",
    "psd", "xcf", "heic", "raw", "cr2", "nef",
    // fonts
    "woff", "woff2", "ttf", "otf", "eot",
    // archives
    "zip", "tar", "gz", "tgz", "bz2", "xz", "zst", "7z", "rar", "jar", "war", "ear",
    "apk", "aab", "ipa", "deb", "rpm", "dmg", "iso", "whl", "egg", "nupkg", "crx",
    // audio and video
    "mp3", "mp4", "m4a", "m4v", "wav", "ogg", "oga", "flac", "aac", "opus", "mov",
    "avi", "mkv", "webm", "wmv", "flv", "mid", "midi",
    // documents
    "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "odt", "ods", "odp", "epub",
    "key", "numbers", "pages",
    // compiled and data
    "exe", "dll", "so", "dylib", "o", "obj", "a", "lib", "class", "pyc", "pyo",
    "wasm", "bin", "dat", "db", "sqlite", "sqlite3", "mdb", "pkl", "pickle", "npy",
    "npz", "h5", "hdf5", "onnx", "pt", "pth", "ckpt", "safetensors", "parquet",
    "avro", "orc", "feather", "tfrecord", "blend", "fbx", "glb", "3ds", "dwg",
    "sketch", "fig", "swf", "keystore", "jks", "p12", "pfx", "der",
  ];

  const BINARY_SET = new Set(BINARY_EXTENSIONS);
  const LOCK_SET = new Set(LOCKFILES);
  const JUNK_SET = new Set(JUNK_FILES);
  const DIR_SET = new Set(IGNORED_DIRS);

  const DEFAULTS = {
    maxFileSize: 512 * 1024,
    maxTotalSize: 0, // 0 means no limit
    includeLockfiles: false,
    includeMinified: false,
    useGitignore: true,
    contents: true,
    include: [],
    exclude: [],
    subdir: "",
  };

  function extname(path) {
    const name = basename(path);
    const dot = name.lastIndexOf(".");
    return dot > 0 ? name.slice(dot + 1).toLowerCase() : "";
  }

  function basename(path) {
    const slash = path.lastIndexOf("/");
    return slash === -1 ? path : path.slice(slash + 1);
  }

  function isMinified(path) {
    const name = basename(path).toLowerCase();
    return /\.min\.(js|mjs|cjs|css)$/.test(name) || name.endsWith(".map");
  }

  // Returns the first ignored-by-default folder in the path, or null.
  function ignoredDirOf(path) {
    const parts = path.split("/");
    for (let i = 0; i < parts.length - 1; i++) {
      if (DIR_SET.has(parts[i])) return parts.slice(0, i + 1).join("/");
    }
    return null;
  }

  // entries: [{ path, size, type? }] where type can be "file" or "symlink".
  // ignoreFiles: { ".gitignore": text, "src/.gitignore": text, ".gittomdignore": text }
  // Returns { selected: [entry], skipped: [{ path, size, reason, dir? }] }.
  function planEntries(entries, options = {}, ignoreFiles = {}) {
    const opts = { ...DEFAULTS, ...options };
    const subdir = normaliseSubdir(opts.subdir);

    const gitRules = [];
    const ownRules = [];
    const ignorePaths = Object.keys(ignoreFiles).sort((a, b) => a.split("/").length - b.split("/").length);
    for (const file of ignorePaths) {
      const slash = file.lastIndexOf("/");
      const base = slash === -1 ? "" : file.slice(0, slash);
      const name = basename(file);
      if (name === ".gitignore" && opts.useGitignore) gitRules.push(...parseIgnore(ignoreFiles[file], base));
      if (name === ".gittomdignore") ownRules.push(...parseIgnore(ignoreFiles[file], base));
    }
    const gitIgnored = createMatcher(gitRules);
    const ownIgnored = createMatcher(ownRules);
    const included = createGlobList(opts.include);
    const excluded = createGlobList(opts.exclude);

    const selected = [];
    const skipped = [];
    let total = 0;

    const sorted = [...entries].sort((a, b) => comparePaths(a.path, b.path));
    for (const entry of sorted) {
      const { path } = entry;
      const size = entry.size || 0;
      const skip = (reason, dir) => skipped.push({ path, size, reason, ...(dir ? { dir } : {}) });

      if (subdir && !path.startsWith(subdir + "/")) continue;

      const dir = ignoredDirOf(path);
      if (dir) { skip("ignored-dir", dir); continue; }
      if (JUNK_SET.has(basename(path))) continue;
      if (entry.type === "symlink") { skip("symlink"); continue; }
      if (ownIgnored(path)) { skip("gittomdignore"); continue; }
      if (gitIgnored(path)) { skip("gitignore"); continue; }
      if (excluded && excluded(path)) { skip("exclude"); continue; }
      if (included && !included(path)) { skip("not-included"); continue; }
      if (!opts.includeLockfiles && LOCK_SET.has(basename(path))) { skip("lockfile"); continue; }
      if (BINARY_SET.has(extname(path))) { skip("binary"); continue; }
      if (!opts.includeMinified && isMinified(path)) { skip("minified"); continue; }
      if (opts.maxFileSize && size > opts.maxFileSize) { skip("too-large"); continue; }
      if (!opts.contents) { skip("no-contents"); continue; }
      if (opts.maxTotalSize && total + size > opts.maxTotalSize) { skip("total-limit"); continue; }
      total += size;
      selected.push(entry);
    }
    return { selected, skipped };
  }

  // Paths of every ignore file among the entries, so callers can load them first.
  function ignoreFilePaths(entries) {
    return entries
      .map((e) => e.path)
      .filter((p) => {
        const name = basename(p);
        return (name === ".gitignore" || name === ".gittomdignore") && !ignoredDirOf(p);
      });
  }

  function normaliseSubdir(value) {
    return String(value || "").replace(/^\/+|\/+$/g, "");
  }

  // Folders first, then files, case-insensitive. Same order as the tree.
  function comparePaths(a, b) {
    const pa = a.split("/");
    const pb = b.split("/");
    const n = Math.min(pa.length, pb.length);
    for (let i = 0; i < n; i++) {
      if (pa[i] === pb[i]) continue;
      const aIsDir = i < pa.length - 1;
      const bIsDir = i < pb.length - 1;
      if (aIsDir !== bIsDir) return aIsDir ? -1 : 1;
      const x = pa[i].toLowerCase();
      const y = pb[i].toLowerCase();
      if (x !== y) return x < y ? -1 : 1;
      return pa[i] < pb[i] ? -1 : 1;
    }
    return pa.length - pb.length;
  }

  // Decodes file bytes as text. Returns null when the file looks binary:
  // a NUL byte in the first 8000 bytes, or bytes that are not valid UTF-8.
  function decodeText(bytes) {
    const head = bytes.subarray(0, 8000);
    for (let i = 0; i < head.length; i++) if (head[i] === 0) return null;
    try {
      let text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
      if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);
      return text;
    } catch {
      return null;
    }
  }

  // ---- languages.js ----
  // File extension or name to the language tag of a Markdown code block.

  const BY_EXT = {
    js: "javascript", mjs: "javascript", cjs: "javascript", jsx: "jsx",
    ts: "typescript", mts: "typescript", cts: "typescript", tsx: "tsx",
    py: "python", pyi: "python", pyw: "python", ipynb: "json",
    rb: "ruby", php: "php", java: "java", kt: "kotlin", kts: "kotlin",
    scala: "scala", groovy: "groovy", gradle: "groovy", go: "go", rs: "rust",
    c: "c", h: "c", cc: "cpp", cpp: "cpp", cxx: "cpp", hpp: "cpp", hh: "cpp", hxx: "cpp",
    cs: "csharp", fs: "fsharp", vb: "vbnet", swift: "swift", m: "objectivec", mm: "objectivec",
    dart: "dart", lua: "lua", r: "r", jl: "julia", pl: "perl", pm: "perl",
    ex: "elixir", exs: "elixir", erl: "erlang", hrl: "erlang", hs: "haskell",
    clj: "clojure", cljs: "clojure", ml: "ocaml", mli: "ocaml", elm: "elm",
    nim: "nim", zig: "zig", v: "v", sol: "solidity", asm: "asm", s: "asm",
    sh: "bash", bash: "bash", zsh: "bash", fish: "fish", ps1: "powershell", psm1: "powershell",
    bat: "bat", cmd: "bat",
    html: "html", htm: "html", xhtml: "html", vue: "vue", svelte: "svelte", astro: "astro",
    css: "css", scss: "scss", sass: "sass", less: "less", styl: "stylus",
    json: "json", jsonc: "jsonc", json5: "json5", yaml: "yaml", yml: "yaml",
    toml: "toml", ini: "ini", cfg: "ini", conf: "conf", env: "bash", properties: "properties",
    xml: "xml", svg: "xml", xsd: "xml", xsl: "xml", plist: "xml", csproj: "xml",
    md: "markdown", mdx: "mdx", markdown: "markdown", rst: "rst", adoc: "asciidoc",
    tex: "latex", sty: "latex", cls: "latex", bib: "bibtex",
    sql: "sql", graphql: "graphql", gql: "graphql", proto: "protobuf", prisma: "prisma",
    tf: "hcl", tfvars: "hcl", hcl: "hcl", nix: "nix", dockerfile: "dockerfile",
    mk: "makefile", cmake: "cmake", csv: "csv", tsv: "tsv", txt: "text", log: "text",
    diff: "diff", patch: "diff", vim: "vim", el: "elisp", lisp: "lisp", scm: "scheme",
    pas: "pascal", f90: "fortran", f: "fortran", cob: "cobol", ada: "ada", d: "d",
    cr: "crystal", hx: "haxe", tcl: "tcl", awk: "awk", sed: "sed", pug: "pug",
    hbs: "handlebars", ejs: "ejs", erb: "erb", j2: "jinja", jinja: "jinja", twig: "twig",
    liquid: "liquid", glsl: "glsl", hlsl: "hlsl", wgsl: "wgsl", cu: "cuda",
  };

  const BY_NAME = {
    dockerfile: "dockerfile", containerfile: "dockerfile", makefile: "makefile",
    gnumakefile: "makefile", cmakelists: "cmake", "cmakelists.txt": "cmake",
    rakefile: "ruby", gemfile: "ruby", podfile: "ruby", vagrantfile: "ruby",
    jenkinsfile: "groovy", procfile: "yaml", justfile: "makefile",
    ".gitignore": "gitignore", ".dockerignore": "gitignore", ".gittomdignore": "gitignore",
    ".npmignore": "gitignore", ".gitattributes": "gitattributes", ".editorconfig": "ini",
    ".bashrc": "bash", ".zshrc": "bash", ".profile": "bash", ".env": "bash",
    "license": "text", "copying": "text", "authors": "text",
  };

  function languageFor(path) {
    const name = path.slice(path.lastIndexOf("/") + 1).toLowerCase();
    if (BY_NAME[name]) return BY_NAME[name];
    if (name.startsWith("dockerfile")) return "dockerfile";
    if (name.startsWith(".env")) return "bash";
    const dot = name.lastIndexOf(".");
    if (dot <= 0) return "";
    return BY_EXT[name.slice(dot + 1)] || "";
  }

  // ---- tree.js ----
  // Folder tree in plain ASCII, like `tree --charset=ascii`.


  // files: list of paths. marks: Map(path -> suffix text) for files and for
  // collapsed folders. collapsed: Set of folder paths shown without children.
  function renderTree(rootName, files, { marks = new Map(), collapsed = new Set() } = {}) {
    const root = { name: rootName, dirs: new Map(), files: [] };

    for (const path of [...files].sort(comparePaths)) {
      const parts = path.split("/");
      let node = root;
      let prefix = "";
      let hidden = false;
      for (let i = 0; i < parts.length - 1; i++) {
        prefix = prefix ? prefix + "/" + parts[i] : parts[i];
        if (!node.dirs.has(parts[i])) node.dirs.set(parts[i], { name: parts[i], path: prefix, dirs: new Map(), files: [] });
        node = node.dirs.get(parts[i]);
        if (collapsed.has(prefix)) { hidden = true; break; }
      }
      if (!hidden) node.files.push({ name: parts[parts.length - 1], path });
    }

    const lines = [rootName + "/"];
    walk(root, "", lines, marks, collapsed);
    return lines.join("\n");
  }

  function walk(node, indent, lines, marks, collapsed) {
    const children = [
      ...[...node.dirs.values()].map((d) => ({ dir: true, ...d })),
      ...node.files.map((f) => ({ dir: false, ...f })),
    ];
    children.forEach((child, i) => {
      const last = i === children.length - 1;
      const mark = marks.get(child.path);
      const label = child.name + (child.dir ? "/" : "") + (mark ? "  " + mark : "");
      lines.push(indent + (last ? "`-- " : "|-- ") + label);
      if (child.dir && !collapsed.has(child.path)) {
        walk(child, indent + (last ? "    " : "|   "), lines, marks, collapsed);
      }
    });
  }

  // ---- tokens.js ----
  // Rough token count without a tokenizer. Modern tokenizers average about four
  // characters per token on English text and code; text with many non-Latin
  // characters uses more tokens, so those count more. The number is an estimate
  // meant to tell whether the file fits a model's context, not an exact bill.

  function estimateTokens(text) {
    if (!text) return 0;
    let ascii = 0;
    let other = 0;
    for (let i = 0; i < text.length; i++) {
      if (text.charCodeAt(i) < 128) ascii++;
      else other++;
    }
    return Math.ceil(ascii / 4 + other / 1.5);
  }

  function formatTokens(n) {
    if (n < 1000) return String(n);
    if (n < 1e6) return (n / 1000).toFixed(n < 10000 ? 1 : 0) + "k";
    return (n / 1e6).toFixed(2) + "M";
  }

  function formatBytes(n) {
    if (n < 1024) return n + " B";
    if (n < 1024 * 1024) return (n / 1024).toFixed(1) + " KB";
    return (n / 1024 / 1024).toFixed(1) + " MB";
  }

  // Accepts "500", "500k", "2M", "512KB", "1.5mb". Returns bytes (or a count
  // when used for tokens). Returns NaN on bad input.
  function parseSize(value) {
    const m = String(value).trim().match(/^(\d+(?:\.\d+)?)\s*([kmg]?)b?$/i);
    if (!m) return NaN;
    const mult = { "": 1, k: 1024, m: 1024 ** 2, g: 1024 ** 3 }[m[2].toLowerCase()];
    return Math.round(parseFloat(m[1]) * mult);
  }

  function parseCount(value) {
    const m = String(value).trim().match(/^(\d+(?:\.\d+)?)\s*([km]?)$/i);
    if (!m) return NaN;
    const mult = { "": 1, k: 1000, m: 1e6 }[m[2].toLowerCase()];
    return Math.round(parseFloat(m[1]) * mult);
  }

  // ---- markdown.js ----
  // Builds the Markdown document from the selected files and the skipped list.


  // A fence one backtick longer than the longest run inside the text, so a file
  // that contains ``` itself cannot close the block early.
  function fenceFor(text) {
    let longest = 0;
    const runs = String(text).match(/`+/g);
    if (runs) for (const r of runs) longest = Math.max(longest, r.length);
    return "`".repeat(Math.max(3, longest + 1));
  }

  function inlineCode(text) {
    const s = String(text);
    if (!s.includes("`")) return "`" + s + "`";
    const fence = "`".repeat(Math.max(...s.match(/`+/g).map((r) => r.length)) + 1);
    return fence + " " + s + " " + fence;
  }

  function cell(text) {
    return String(text).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
  }

  // Root README first, then the tree order: the README is what a person would
  // read first too.
  function orderFiles(files) {
    const sorted = [...files].sort((a, b) => comparePaths(a.path, b.path));
    const isReadme = (f) => !f.path.includes("/") && /^readme(\.|$)/i.test(f.path);
    return [...sorted.filter(isReadme), ...sorted.filter((f) => !isReadme(f))];
  }

  function fileBlock(file, lang) {
    const content = file.content.replace(/\s+$/, "");
    const fence = fenceFor(content);
    const heading = "### " + inlineCode(file.path);
    if (!content) return heading + "\n\n" + t(lang, "emptyFile") + "\n";
    return heading + "\n\n" + fence + languageFor(file.path) + "\n" + content + "\n" + fence + "\n";
  }

  const MAX_SKIPPED_ROWS = 500;

  function skippedSection(skipped, lang) {
    if (!skipped.length) return "";
    const rows = [];
    const dirs = new Map();
    for (const s of skipped) {
      if (s.dir) dirs.set(s.dir, (dirs.get(s.dir) || 0) + 1);
      else rows.push([s.path, t(lang, "reasons." + s.reason)]);
    }
    for (const [dir, n] of dirs) {
      rows.push([dir + "/", t(lang, "reasons.ignored-dir") + " (" + t(lang, "filesInside", { n }) + ")"]);
    }
    rows.sort((a, b) => comparePaths(a[0], b[0]));
    const shown = rows.slice(0, MAX_SKIPPED_ROWS);
    let out = "## " + t(lang, "skippedTitle") + "\n\n" + t(lang, "skippedIntro") + "\n\n";
    out += "| " + t(lang, "file") + " | " + t(lang, "reason") + " |\n|---|---|\n";
    for (const [p, r] of shown) out += "| " + cell(inlineCode(p)) + " | " + cell(r) + " |\n";
    if (rows.length > shown.length) out += "\n" + t(lang, "more", { n: rows.length - shown.length }) + "\n";
    return out;
  }

  function treeSection(opts, files, skipped, lang) {
    const marks = new Map();
    const collapsed = new Set();
    const paths = files.map((f) => f.path);
    for (const s of skipped) {
      if (s.dir) {
        collapsed.add(s.dir);
        paths.push(s.path);
        marks.set(s.dir, t(lang, "omittedMark"));
      } else {
        paths.push(s.path);
        marks.set(s.path, t(lang, "omittedMark"));
      }
    }
    const tree = renderTree(opts.rootName || "repo", paths, { marks, collapsed });
    const fence = fenceFor(tree);
    return "## " + t(lang, "structure") + "\n\n" + fence + "text\n" + tree + "\n" + fence + "\n";
  }

  /**
   * opts:
   *   title        heading of the document, for example "owner/repo"
   *   rootName     name of the root folder in the tree
   *   meta         { source, description, ref, commit, date }
   *   lang         "es" or "en"
   *   prompt       true for the default text, a string for a custom one, false for none
   *   tree         include the tree (default true)
   *   split        max tokens per part, 0 for a single document
   * files: [{ path, content, size }]
   * skipped: [{ path, size, reason, dir? }]
   * Returns { parts: [string], tokens, bytes, fileCount, skippedCount }.
   */
  function buildMarkdown(opts, files, skipped) {
    const lang = opts.lang || "es";
    const meta = opts.meta || {};
    const title = opts.title || opts.rootName || "repo";
    const ordered = orderFiles(files);
    const blocks = ordered.map((f) => fileBlock(f, lang));
    const bytes = files.reduce((n, f) => n + (f.size || 0), 0);

    const treeText = opts.tree === false ? "" : treeSection(opts, files, skipped, lang);
    const skippedText = skippedSection(skipped, lang);
    const promptText =
      opts.prompt === false || opts.prompt === undefined
        ? ""
        : typeof opts.prompt === "string" && opts.prompt.trim()
          ? opts.prompt.trim()
          : t(lang, "defaultPrompt", { repo: title });

    const bodyTokens = estimateTokens(treeText + skippedText + blocks.join("\n"));

    // Split the file blocks into parts when asked.
    const chunks = [];
    if (opts.split && opts.split > 0) {
      let current = [];
      let size = estimateTokens(treeText) + 400;
      for (const b of blocks) {
        const bt = estimateTokens(b);
        if (current.length && size + bt > opts.split) {
          chunks.push(current);
          current = [];
          size = 100;
        }
        current.push(b);
        size += bt;
      }
      chunks.push(current);
    } else {
      chunks.push(blocks);
    }
    const total = chunks.length;

    function header(tokens) {
      let out = "# " + title + "\n\n" + t(lang, "generatedBy", { date: meta.date || new Date().toISOString().slice(0, 10) }) + "\n\n";
      if (promptText) out += "## " + t(lang, "promptTitle") + "\n\n" + promptText + "\n\n";
      out += "## " + t(lang, "summary") + "\n\n| | |\n|---|---|\n";
      const row = (k, v) => { if (v !== undefined && v !== null && v !== "") out += "| " + t(lang, k) + " | " + cell(v) + " |\n"; };
      row("source", meta.source);
      row("description", meta.description);
      row("ref", meta.ref);
      row("commit", meta.commit);
      row("included", files.length);
      row("skipped", skipped.length);
      row("size", formatBytes(bytes));
      row("tokens", "~" + formatTokens(tokens));
      if (total > 1) row("part", "1 " + t(lang, "of") + " " + total);
      return out;
    }

    const headTokens = estimateTokens(header(bodyTokens));
    const tokens = bodyTokens + headTokens;

    const parts = chunks.map((chunk, i) => {
      let out = "";
      if (i === 0) {
        out += header(tokens) + "\n";
        if (treeText) out += treeText + "\n";
      } else {
        out += "# " + title + " (" + t(lang, "part").toLowerCase() + " " + (i + 1) + " " + t(lang, "of") + " " + total + ")\n\n";
      }
      if (chunk.length) out += "## " + t(lang, "files") + "\n\n" + chunk.join("\n") + "\n";
      if (i === total - 1 && skippedText) out += skippedText;
      return out.replace(/\s*$/, "\n");
    });

    return { parts, tokens, bytes, fileCount: files.length, skippedCount: skipped.length };
  }

  // ---- github.js ----
  // Reading repository input and talking to the GitHub REST API with fetch.
  // Runs the same in Node 18+ and in the browser.

  const API = "https://api.github.com";

  class GitHubError extends Error {
    constructor(message, { status = 0, kind = "other", reset = null } = {}) {
      super(message);
      this.name = "GitHubError";
      this.status = status;
      this.kind = kind; // "not-found" | "rate-limit" | "auth" | "network" | "other"
      this.reset = reset; // Date when the rate limit resets, if known
    }
  }

  const NAME = /^[A-Za-z0-9_.-]+$/;

  // Accepts:
  //   https://github.com/owner/repo
  //   https://github.com/owner/repo.git
  //   https://github.com/owner/repo/tree/<ref>/<subdir>
  //   github.com/owner/repo, git@github.com:owner/repo.git
  //   owner/repo, owner/repo@ref
  // Returns { owner, repo, ref, subdir } or null when it is not a GitHub repo.
  function parseRepoInput(input) {
    let s = String(input || "").trim();
    if (!s) return null;
    let ref = "";
    let subdir = "";

    const ssh = s.match(/^git@github\.com:([^/]+)\/(.+?)(?:\.git)?\/?$/i);
    if (ssh) return valid(ssh[1], ssh[2], "", "");

    const url = s.match(/^(?:https?:\/\/)?(?:www\.)?github\.com\/(.*)$/i);
    if (url) {
      const rest = url[1].split(/[?#]/)[0].replace(/\/+$/, "");
      const parts = rest.split("/").filter(Boolean);
      if (parts.length < 2) return null;
      const [owner, rawRepo, kind, ...more] = parts;
      const repo = rawRepo.replace(/\.git$/i, "");
      if ((kind === "tree" || kind === "blob" || kind === "commit") && more.length) {
        ref = decodeURIComponent(more[0]);
        subdir = more.slice(1).map(decodeURIComponent).join("/");
        if (kind === "blob") subdir = subdir.split("/").slice(0, -1).join("/");
      }
      return valid(owner, repo, ref, subdir);
    }

    // owner/repo or owner/repo@ref, and nothing that looks like a local path
    if (/^[.~/\\]/.test(s) || /^[A-Za-z]:[\\/]/.test(s)) return null;
    const at = s.lastIndexOf("@");
    if (at > 0) {
      ref = s.slice(at + 1);
      s = s.slice(0, at);
    }
    const parts = s.split("/");
    if (parts.length !== 2) return null;
    return valid(parts[0], parts[1].replace(/\.git$/i, ""), ref, "");
  }

  function valid(owner, repo, ref, subdir) {
    if (!NAME.test(owner) || !NAME.test(repo)) return null;
    return { owner, repo, ref, subdir };
  }

  function headers(token, accept) {
    const h = { Accept: accept || "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" };
    if (token) h.Authorization = "Bearer " + token;
    return h;
  }

  // Throws a GitHubError with a useful kind for the common failures.
  async function checkResponse(res, what) {
    if (res.ok) return res;
    const remaining = res.headers.get("x-ratelimit-remaining");
    const resetHeader = res.headers.get("x-ratelimit-reset");
    const reset = resetHeader ? new Date(Number(resetHeader) * 1000) : null;
    let message = "";
    try {
      const body = await res.json();
      message = body && body.message ? body.message : "";
    } catch {
      /* the body is not JSON */
    }
    if (res.status === 404) throw new GitHubError(what + ": not found", { status: 404, kind: "not-found" });
    if ((res.status === 403 || res.status === 429) && (remaining === "0" || /rate limit/i.test(message))) {
      throw new GitHubError("GitHub API rate limit reached", { status: res.status, kind: "rate-limit", reset });
    }
    if (res.status === 401) throw new GitHubError("the token is not valid or has expired", { status: 401, kind: "auth" });
    if (res.status === 403) throw new GitHubError(message || "access denied", { status: 403, kind: "auth" });
    throw new GitHubError(what + ": HTTP " + res.status + (message ? " (" + message + ")" : ""), { status: res.status });
  }

  async function request(url, { token, accept, fetchImpl } = {}) {
    const f = fetchImpl || globalThis.fetch;
    let res;
    try {
      res = await f(url, { headers: headers(token, accept) });
    } catch (err) {
      throw new GitHubError("network error: " + (err && err.message ? err.message : err), { kind: "network" });
    }
    return res;
  }

  async function getRepo(owner, repo, opts = {}) {
    const res = await request(`${API}/repos/${owner}/${repo}`, opts);
    await checkResponse(res, owner + "/" + repo);
    return res.json();
  }

  // Full commit SHA for a branch, tag or SHA.
  async function getCommitSha(owner, repo, ref, opts = {}) {
    const res = await request(`${API}/repos/${owner}/${repo}/commits/${encodePath(ref)}`, {
      ...opts,
      accept: "application/vnd.github.sha",
    });
    await checkResponse(res, "ref " + ref);
    return (await res.text()).trim();
  }

  // Every path in the commit. Returns { entries: [{ path, size, type }], truncated }.
  async function getTree(owner, repo, sha, opts = {}) {
    const res = await request(`${API}/repos/${owner}/${repo}/git/trees/${sha}?recursive=1`, opts);
    await checkResponse(res, "tree " + sha);
    const data = await res.json();
    const entries = [];
    for (const item of data.tree || []) {
      if (item.type !== "blob") continue; // folders and submodules
      const type = item.mode === "120000" ? "symlink" : "file";
      entries.push({ path: item.path, size: item.size || 0, type });
    }
    return { entries, truncated: Boolean(data.truncated) };
  }

  function encodePath(path) {
    return path.split("/").map(encodeURIComponent).join("/");
  }

  // URL to download one file. Public repos use raw.githubusercontent.com, which
  // does not count against the API limit; private ones need the API.
  function fileUrl(owner, repo, sha, path, isPrivate) {
    if (!isPrivate) return `https://raw.githubusercontent.com/${owner}/${repo}/${sha}/${encodePath(path)}`;
    return `${API}/repos/${owner}/${repo}/contents/${encodePath(path)}?ref=${sha}`;
  }

  async function getFileBytes(owner, repo, sha, path, { token, isPrivate, fetchImpl } = {}) {
    const url = fileUrl(owner, repo, sha, path, isPrivate);
    const f = fetchImpl || globalThis.fetch;
    const init = isPrivate ? { headers: headers(token, "application/vnd.github.raw") } : {};
    let res;
    try {
      res = await f(url, init);
    } catch (err) {
      throw new GitHubError("network error: " + (err && err.message ? err.message : err), { kind: "network" });
    }
    await checkResponse(res, path);
    return new Uint8Array(await res.arrayBuffer());
  }

  // A URL like /tree/feature/login/src is ambiguous: the branch may be "feature"
  // or "feature/login". Tries the shortest ref first and moves folder parts into
  // the ref until one exists. Returns { sha, ref, subdir }.
  async function resolveRef(owner, repo, ref, subdir, opts = {}) {
    const parts = subdir ? subdir.split("/") : [];
    let candidate = ref;
    for (let i = 0; ; i++) {
      try {
        const sha = await getCommitSha(owner, repo, candidate, opts);
        return { sha, ref: candidate, subdir: parts.slice(i).join("/") };
      } catch (err) {
        if (err.kind !== "not-found" && err.status !== 422) throw err;
        if (i >= parts.length) throw err;
        candidate += "/" + parts[i];
      }
    }
  }

  function tarballUrl(owner, repo, ref) {
    return `${API}/repos/${owner}/${repo}/tarball/${encodePath(ref)}`;
  }

  function requestHeaders(token, accept) {
    return headers(token, accept);
  }

  global.GitToMd = { version: "1.0.1", MESSAGES, pickLang, t, globToRegExp, parseIgnore, createMatcher, createGlobList, IGNORED_DIRS, LOCKFILES, JUNK_FILES, BINARY_EXTENSIONS, DEFAULTS, extname, basename, isMinified, planEntries, ignoreFilePaths, normaliseSubdir, comparePaths, decodeText, languageFor, renderTree, estimateTokens, formatTokens, formatBytes, parseSize, parseCount, fenceFor, inlineCode, buildMarkdown, API, GitHubError, parseRepoInput, checkResponse, getRepo, getCommitSha, getTree, fileUrl, getFileBytes, resolveRef, tarballUrl, requestHeaders };
})(typeof window !== "undefined" ? window : globalThis);
