// Bundles src/core into one classic script for the browser, exposed as
// window.GitToMd. No bundler: the core modules only use relative imports and
// named exports, so it is enough to drop those lines and wrap the rest.
//
//   node scripts/build-web.mjs           writes web/js/gittomd-core.js
//   node scripts/build-web.mjs --check   fails if dist/ is out of date

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const ORDER = ["i18n", "gitignore", "filters", "languages", "tree", "tokens", "markdown", "github"];
const version = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")).version;

const names = [];
let body = "";
for (const mod of ORDER) {
  let src = fs.readFileSync(path.join(root, "src/core", mod + ".js"), "utf8");
  src = src.replace(/^import[^;]+;\n/gm, "");
  src = src.replace(/^export (async function|function|class|const|let) ([A-Za-z0-9_$]+)/gm, (_, kind, name) => {
    names.push(name);
    return kind + " " + name;
  });
  if (/^\s*export\s/m.test(src)) throw new Error(mod + ".js has an export this script does not understand");
  body += "\n  // ---- " + mod + ".js ----\n" + src.replace(/^(?=.)/gm, "  ");
}

const out =
  "// gittomd core " + version + " for the browser. Generated by scripts/build-web.mjs; do not edit.\n" +
  "// https://github.com/Ismael-Sallami/gittomd (MIT)\n" +
  "(function (global) {\n  \"use strict\";\n" + body +
  "\n  global.GitToMd = { version: " + JSON.stringify(version) + ", " + names.join(", ") + " };\n" +
  "})(typeof window !== \"undefined\" ? window : globalThis);\n";

const file = path.join(root, "web/js/gittomd-core.js");
if (process.argv.includes("--check")) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
  if (current !== out) {
    console.error("web/js/gittomd-core.js is out of date: run npm run build:web");
    process.exit(1);
  }
  console.log("web/js/gittomd-core.js is up to date");
} else {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, out);
  console.log("wrote " + path.relative(root, file) + " (" + names.length + " exports)");
}
